### ISSUE TITLE
binutils build error

### ISSUE THREAD

**Issue by willgdjones** [cosmo0920/homebrew-mingw_w64#15] opened 2017-01-27 17:03 UTC
Hi there - I'm getting a build error and I'd appreciate some help.

It seems to have trouble building bin-utils, but it's unclear to me what the fix is.

checking for C compiler default output file name...
configure: error: in `/nfs/gns/homes/willj/.linuxbrew/Library/Taps/cosmo0920/homebrew-mingw_w64/cmd/source/binutils-2.26.1/build':
configure: error: C compiler cannot create executables
See `config.log' for more details.

Thanks in advance

I've included the config.log file too. Note that I don't have root on my machine.

$ ../configure --target=i686-w64-mingw32 --disable-werror --disable-multilib --prefix=/nfs/gns/homes/willj/.linuxbrew/Cellar/mingw-w64/4.0.6 --with-sysroot=/nfs/gns/homes/willj/.linuxbrew/Cellar/mingw-w64/4.0.6

## --------- ##

hostname = gpu-002.ebi.ac.uk
uname -m = x86_64
uname -r = 3.10.0-327.10.1.el7.x86_64
uname -s = Linux
uname -v = #1 SMP Sat Jan 23 04:54:55 EST 2016

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /nfs/gns/homes/willj/.linuxbrew/bin
PATH: /nfs/gns/homes/willj/.linuxbrew/sbin
PATH: /nfs/gns/homes/willj/anaconda3/bin
PATH: /homes/willj/anaconda3/envs/GTEx/bin
PATH: /nfs/gns/homes/willj/.linuxbrew/bin
PATH: /nfs/gns/homes/willj/.linuxbrew/sbin
PATH: /nfs/gns/homes/willj/anaconda3/bin
PATH: /usr/lib64/qt-3.3/bin
PATH: /ebi/lsf/ebi/9.1/linux2.6-glibc2.3-x86_64/etc
PATH: /ebi/lsf/ebi/9.1/linux2.6-glibc2.3-x86_64/bin
PATH: /usr/kerberos/sbin
PATH: /usr/kerberos/bin
PATH: /usr/lpp/mmfs/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /usr/local/sbin
PATH: /usr/sbin
PATH: /nfs/gns/homes/will/bin
PATH: /homes/willj/bin
PATH: /nfs/gns/homes/will/bin
PATH: /nfs/gns/homes/willj/.linuxbrew/Library/Taps/cosmo0920/homebrew-mingw_w64/cmd
PATH: /nfs/gns/homes/willj/.linuxbrew/Library/Homebrew/cask/cmd
PATH: /nfs/gns/homes/willj/.linuxbrew/Library/Homebrew/shims/scm

## ----------- ##

configure:2296: checking build system type
configure:2310: result: x86_64-pc-linux-gnu
configure:2357: checking host system type
configure:2370: result: x86_64-pc-linux-gnu
configure:2390: checking target system type
configure:2403: result: i686-w64-mingw32
configure:2457: checking for a BSD-compatible install
configure:2525: result: /usr/bin/install -c
configure:2536: checking whether ln works
configure:2558: result: yes
configure:2562: checking whether ln -s works
configure:2566: result: yes
configure:2573: checking for a sed that does not truncate output
configure:2637: result: /usr/bin/sed
configure:2646: checking for gawk
configure:2662: found /usr/bin/gawk
configure:2673: result: gawk
configure:4111: checking for gcc
configure:4138: result: gcc-6
configure:4367: checking for C compiler version
configure:4376: gcc-6 --version >&5
../configure: line 4378: gcc-6: command not found
configure:4387: $? = 127
configure:4376: gcc-6 -v >&5
../configure: line 4378: gcc-6: command not found
configure:4387: $? = 127
configure:4376: gcc-6 -V >&5
../configure: line 4378: gcc-6: command not found
configure:4387: $? = 127
configure:4376: gcc-6 -qversion >&5
../configure: line 4378: gcc-6: command not found
configure:4387: $? = 127
configure:4407: checking for C compiler default output file name
configure:4429: gcc-6    conftest.c  >&5
../configure: line 4431: gcc-6: command not found
configure:4433: $? = 127
configure:4470: result:
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:4476: error: in `/nfs/gns/homes/willj/.linuxbrew/Library/Taps/cosmo0920/homebrew-mingw_w64/cmd/source/binutils-2.26.1/build':
configure:4480: error: C compiler cannot create executables
See `config.log' for more details.

## ---------------- ##

ac_cv_build=x86_64-pc-linux-gnu
ac_cv_env_AR_FOR_TARGET_set=
ac_cv_env_AR_FOR_TARGET_value=
ac_cv_env_AR_set=
ac_cv_env_AR_value=
ac_cv_env_AS_FOR_TARGET_set=
ac_cv_env_AS_FOR_TARGET_value=
ac_cv_env_AS_set=
ac_cv_env_AS_value=
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_FOR_TARGET_set=
ac_cv_env_CC_FOR_TARGET_value=
ac_cv_env_CC_set=set
ac_cv_env_CC_value=gcc-6
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_FOR_TARGET_set=
ac_cv_env_CXX_FOR_TARGET_value=
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=g++-6
ac_cv_env_DLLTOOL_FOR_TARGET_set=
ac_cv_env_DLLTOOL_FOR_TARGET_value=
ac_cv_env_DLLTOOL_set=
ac_cv_env_DLLTOOL_value=
ac_cv_env_GCC_FOR_TARGET_set=
ac_cv_env_GCC_FOR_TARGET_value=
ac_cv_env_GCJ_FOR_TARGET_set=
ac_cv_env_GCJ_FOR_TARGET_value=
ac_cv_env_GFORTRAN_FOR_TARGET_set=
ac_cv_env_GFORTRAN_FOR_TARGET_value=
ac_cv_env_GOC_FOR_TARGET_set=
ac_cv_env_GOC_FOR_TARGET_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LD_FOR_TARGET_set=
ac_cv_env_LD_FOR_TARGET_value=
ac_cv_env_LD_set=set
ac_cv_env_LD_value=gcc-6
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LIPO_FOR_TARGET_set=
ac_cv_env_LIPO_FOR_TARGET_value=
ac_cv_env_LIPO_set=
ac_cv_env_LIPO_value=
ac_cv_env_NM_FOR_TARGET_set=
ac_cv_env_NM_FOR_TARGET_value=
ac_cv_env_NM_set=
ac_cv_env_NM_value=
ac_cv_env_OBJCOPY_FOR_TARGET_set=
ac_cv_env_OBJCOPY_FOR_TARGET_value=
ac_cv_env_OBJCOPY_set=
ac_cv_env_OBJCOPY_value=
ac_cv_env_OBJDUMP_FOR_TARGET_set=
ac_cv_env_OBJDUMP_FOR_TARGET_value=
ac_cv_env_OBJDUMP_set=
ac_cv_env_OBJDUMP_value=
ac_cv_env_RANLIB_FOR_TARGET_set=
ac_cv_env_RANLIB_FOR_TARGET_value=
ac_cv_env_RANLIB_set=
ac_cv_env_RANLIB_value=
ac_cv_env_READELF_FOR_TARGET_set=
ac_cv_env_READELF_FOR_TARGET_value=
ac_cv_env_READELF_set=
ac_cv_env_READELF_value=
ac_cv_env_STRIP_FOR_TARGET_set=
ac_cv_env_STRIP_FOR_TARGET_value=
ac_cv_env_STRIP_set=
ac_cv_env_STRIP_value=
ac_cv_env_WINDMC_FOR_TARGET_set=
ac_cv_env_WINDMC_FOR_TARGET_value=
ac_cv_env_WINDMC_set=
ac_cv_env_WINDMC_value=
ac_cv_env_WINDRES_FOR_TARGET_set=
ac_cv_env_WINDRES_FOR_TARGET_value=
ac_cv_env_WINDRES_set=
ac_cv_env_WINDRES_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_build_configargs_set=
ac_cv_env_build_configargs_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_host_configargs_set=
ac_cv_env_host_configargs_value=
ac_cv_env_target_alias_set=set
ac_cv_env_target_alias_value=i686-w64-mingw32
ac_cv_env_target_configargs_set=
ac_cv_env_target_configargs_value=
ac_cv_host=x86_64-pc-linux-gnu
ac_cv_path_SED=/usr/bin/sed
ac_cv_path_install='/usr/bin/install -c'
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc-6
ac_cv_target=i686-w64-mingw32
acx_cv_prog_LN=ln

## ----------------- ##

AR=''
AR_FOR_BUILD='$(AR)'
AR_FOR_TARGET=''
AS=''
AS_FOR_BUILD='$(AS)'
AS_FOR_TARGET=''
AWK='gawk'
BISON=''
BUILD_CONFIG=''
CC='gcc-6'
CC_FOR_BUILD='$(CC)'
CC_FOR_TARGET=''
CFLAGS=''
CFLAGS_FOR_BUILD=''
CFLAGS_FOR_TARGET=''
COMPILER_AS_FOR_TARGET=''
COMPILER_LD_FOR_TARGET=''
COMPILER_NM_FOR_TARGET=''
CONFIGURE_GDB_TK=''
CPPFLAGS=''
CXX='g++-6'
CXXFLAGS=''
CXXFLAGS_FOR_BUILD=''
CXXFLAGS_FOR_TARGET=''
CXX_FOR_BUILD='$(CXX)'
CXX_FOR_TARGET=''
DEBUG_PREFIX_CFLAGS_FOR_TARGET=''
DEFS=''
DLLTOOL=''
DLLTOOL_FOR_BUILD='$(DLLTOOL)'
DLLTOOL_FOR_TARGET=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EXEEXT=''
EXPECT=''
EXTRA_CONFIGARGS_LIBJAVA='--disable-static'
FLAGS_FOR_TARGET=''
FLEX=''
GCC_FOR_TARGET=''
GCC_SHLIB_SUBDIR=''
GCJ_FOR_BUILD='$(GCJ)'
GCJ_FOR_TARGET=''
GDB_TK=''
GFORTRAN_FOR_BUILD='$(GFORTRAN)'
GFORTRAN_FOR_TARGET=''
GNATBIND=''
GNATMAKE=''
GOC_FOR_BUILD='$(GOC)'
GOC_FOR_TARGET=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_GDB_TK=''
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
LD='gcc-6'
LDFLAGS=''
LDFLAGS_FOR_BUILD=''
LDFLAGS_FOR_TARGET=''
LD_FOR_BUILD='$(LD)'
LD_FOR_TARGET=''
LEX=''
LIBOBJS=''
LIBS=''
LIPO=''
LIPO_FOR_TARGET=''
LN='ln'
LN_S='ln -s'
LTLIBOBJS=''
M4=''
MAINT=''
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE=''
MAKEINFO=''
NM=''
NM_FOR_BUILD='$(NM)'
NM_FOR_TARGET=''
OBJCOPY=''
OBJCOPY_FOR_TARGET=''
OBJDUMP=''
OBJDUMP_FOR_TARGET=''
OBJEXT=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_URL=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
RANLIB=''
RANLIB_FOR_BUILD='$(RANLIB)'
RANLIB_FOR_TARGET=''
RAW_CXX_FOR_TARGET=''
READELF=''
READELF_FOR_TARGET=''
RPATH_ENVVAR=''
RUNTEST=''
SED='/usr/bin/sed'
SHELL='/bin/sh'
STRIP=''
STRIP_FOR_TARGET=''
SYSROOT_CFLAGS_FOR_TARGET=''
TOPLEVEL_CONFIGURE_ARGUMENTS='../configure --target=i686-w64-mingw32 --disable-werror --disable-multilib --prefix=/nfs/gns/homes/willj/.linuxbrew/Cellar/mingw-w64/4.0.6 --with-sysroot=/nfs/gns/homes/willj/.linuxbrew/Cellar/mingw-w64/4.0.6'
WINDMC=''
WINDMC_FOR_BUILD='$(WINDMC)'
WINDMC_FOR_TARGET=''
WINDRES=''
WINDRES_FOR_BUILD='$(WINDRES)'
WINDRES_FOR_TARGET=''
YACC=''
ac_ct_CC='gcc-6'
ac_ct_CXX=''
bindir='${exec_prefix}/bin'
build='x86_64-pc-linux-gnu'
build_alias=''
build_configargs=''
build_configdirs='build-libiberty build-libcpp build-texinfo build-flex build-bison build-m4 build-fixincludes'
build_cpu='x86_64'
build_libsubdir='build-x86_64-pc-linux-gnu'
build_noncanonical='x86_64-pc-linux-gnu'
build_os='linux-gnu'
build_subdir='build-x86_64-pc-linux-gnu'
build_tooldir=''
build_vendor='pc'
compare_exclusions=''
configdirs='intl libiberty opcodes bfd readline tcl tk itcl libgui zlib libbacktrace libcpp libdecnumber gmp mpfr mpc isl libelf libiconv texinfo flex bison binutils gas ld fixincludes gcc cgen sid sim gdb gprof etc expect dejagnu m4 utils guile fastjar gnattools libcc1 gotools'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
do_compare=''
docdir='${datarootdir}/doc/${PACKAGE}'
dvidir='${docdir}'
exec_prefix='NONE'
extra_host_libiberty_configure_flags=''
extra_host_zlib_configure_flags=''
extra_isl_gmp_configure_flags=''
extra_liboffloadmic_configure_flags=''
extra_linker_plugin_configure_flags=''
extra_linker_plugin_flags=''
extra_mpc_gmp_configure_flags=''
extra_mpc_mpfr_configure_flags=''
extra_mpfr_configure_flags=''
gmpinc=''
gmplibs=''
host='x86_64-pc-linux-gnu'
host_alias=''
host_configargs=''
host_cpu='x86_64'
host_noncanonical='x86_64-pc-linux-gnu'
host_os='linux-gnu'
host_shared=''
host_subdir='.'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
islinc=''
isllibs=''
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
poststage1_ldflags=''
poststage1_libs=''
prefix='/nfs/gns/homes/willj/.linuxbrew/Cellar/mingw-w64/4.0.6'
program_transform_name='s&^&i686-w64-mingw32-&'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
stage1_cflags=''
stage1_checking=''
stage1_languages=''
stage1_ldflags=''
stage1_libs=''
stage2_werror_flag=''
sysconfdir='${prefix}/etc'
target='i686-w64-mingw32'
target_alias='i686-w64-mingw32'
target_configargs=''
target_configdirs='target-libgcc target-libbacktrace target-libgloss target-newlib target-libgomp target-libcilkrts target-liboffloadmic target-libatomic target-libitm target-libstdc++-v3 target-libsanitizer target-libvtv target-libmpx target-libssp target-libquadmath target-libgfortran target-boehm-gc target-libffi target-zlib target-libjava target-libobjc target-libada target-libgo target-rda'
target_cpu='i686'
target_noncanonical='i686-w64-mingw32'
target_os='mingw32'
target_subdir='i686-w64-mingw32'
target_vendor='w64'
tooldir=''

## ------------------- ##

alphaieee_frag=''
host_makefile_frag='/dev/null'
ospace_frag=''
serialization_dependencies=''
target_makefile_frag=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 77

**Comment by cosmo0920** [comment] 2017-01-27 17:27
This cmd version of shell script is not assumed for linuxbrew environment.  ☹️
It is mainly targeted for OS X Yosemite or later.

**Comment by cosmo0920** [comment] 2017-01-27 17:45
BTW, `gcc-6 --version` works in your environment?

**Comment by cosmo0920** [comment] 2017-01-29 05:39
I've got succeeded to reproduce this issue.
But this issue is caused by lacking of merging gcc 6.x formula from homebrew/homebrew-core into linuxbrew/homebrew-core.

Could you request gcc-6.x formula into linuxbrew?

**Comment by willgdjones** [comment] 2017-01-30 13:07
Thanks and sorry for the slow response. I'll make the issue now.

**Comment by willgdjones** [comment] 2017-01-30 13:09
Nope gcc-6 isn't available in my environment unfortunately.

**Comment by cosmo0920** [comment] 2017-06-28 02:36
@willgdjones Linuxbrew included cross gcc-7 with [mingw-w64](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/mingw-w64.rb) formula.
Could you try this and confirm your unusable cross gcc issue in Linuxbrew?

**Comment by willgdjones** [comment] 2017-06-28 15:28
Hi @cosmo0920 unfortunately it's going to be very hard to recreate what I had done before.

**Comment by willgdjones** [comment] 2017-06-28 15:28
But I managed to find a workaround - I didn't actually need to use mingw-w64 to do what I wanted.

**Comment by cosmo0920** [comment] 2017-07-03 02:08
OK, I'm closing then.

**Closed as completed by cosmo0920** 2017-07-03 02:08 UTC
Labels: linuxbrew, upstream issue
